version: '3'
networks:
  app-net:

services:

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-net

  hefesto:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-net

#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - POSTGRES_DB=mydatabase
#      - POSTGRES_PASSWORD=secret
#      - POSTGRES_USER=myuser
#    ports:
#      - '5432:5432'
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - app-net

  prometheus:
    image: 'prom/prometheus:latest'
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    depends_on:
      - hefesto
    networks:
      - app-net
  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - app-net
#  grafana-agent:
#    image: grafana/agent:v0.22.0
#    volumes:
#      - ./grafana-agent.yaml:/etc/agent-config/grafana-agent.yaml
#      - ./logs/:/var/log/
#    entrypoint:
#      - /bin/agent
#      - -config.file=/etc/agent-config/grafana-agent.yaml
#      - -prometheus.wal-directory=/tmp/agent/wal
#    ports:
#      - "12345:12345"
#    networks:
#      - app-net
#    extra_hosts:
#      - host.docker.internal:host-gateway
volumes:
  postgres-data:

