global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]
